# Generated by Django 3.2.16 on 2022-12-12 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tune',
            name='tune_type',
            field=models.CharField(choices=[('Jig', 'GREEN'), ('Hornpipe', 'BLUE'), ('Reel', 'RED'), ('Polka', 'ORANGE'), ('Setdance', 'YELLOW'), ('Slip Jig', 'PURPLE'), ('Air', 'PINK'), ('Barndance', 'BROWN')], default='Jig', max_length=9),
        ),
        migrations.AlterField(
            model_name='tune',
            name='composer',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='tune',
            name='learned_from',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
