# Generated by Django 3.2.16 on 2022-12-12 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0002_auto_20221212_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tune',
            name='composer',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='tune',
            name='learned_from',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='tune',
            name='tune_type',
            field=models.CharField(choices=[('Jig', 'Jig'), ('Hornpipe', 'Hornpipe'), ('Reel', 'Reel'), ('Polka', 'Polka'), ('Setdance', 'Setdance'), ('Slip Jig', 'Slip Jig'), ('Slow Air', 'Slow Air'), ('Barndance', 'Barndance')], default='Jig', max_length=9),
        ),
    ]
