# Generated by Django 3.2.16 on 2022-12-12 22:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('archive', '0003_auto_20221212_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tune',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='archive_posts', to=settings.AUTH_USER_MODEL),
        ),
    ]
