# Generated by Django 3.2.16 on 2023-01-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0004_alter_tune_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tune',
            name='composer',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='tune',
            name='learned_from',
            field=models.CharField(max_length=200),
        ),
    ]
